connector.name=scylladb
scylladb.contact-points=localhost
scylladb.allow-drop-table=true
scylladb.load-policy.dc-aware.local-dc=datacenter1
scylladb.load-balancing-policy=TokenAwarePolicy
scylladb.consistency-level=ONE
