connector.name=scylladb
# Can be used with `bin/ptl env up --environment multinode-cassandra --without-trino`
scylladb.contact-points=localhost
scylladb.allow-drop-table=true
scylladb.load-policy.dc-aware.local-dc=datacenter1
