# Install a YAML language server in your IDE to validate against the schema, or use a tool
# like https://github.com/yaml-schema/yaml-schema
# yaml-language-server: $schema=./schedule-config-schema.yaml

- modules:
    - [
      client/trino-jdbc,
      core/trino-spi,
      core/trino-web-ui
      ]
- modules:
    - [
      plugin/trino-base-jdbc,
      plugin/trino-faker,
      plugin/trino-geospatial,
      plugin/trino-memory,
      plugin/trino-openlineage,
      plugin/trino-thrift
      ]
- modules:
    - [
      lib/trino-orc,
      lib/trino-parquet
      ]
- modules:
    - [
      lib/trino-filesystem,
      lib/trino-filesystem-azure,
      lib/trino-filesystem-gcs,
      lib/trino-filesystem-manager,
      lib/trino-filesystem-s3,
      lib/trino-hdfs,
      lib/trino-hive-formats,
      plugin/trino-blob-cache-alluxio,
      plugin/trino-blob-cache-memory
      ]
- modules:
    - core/trino-main
- modules:
    - lib/trino-filesystem-azure
  profiles:
    - cloud-tests
- modules:
    - lib/trino-filesystem-gcs
  profiles:
    - cloud-tests
- modules:
    - lib/trino-filesystem-s3
  profiles:
    - cloud-tests
- modules:
    - plugin/trino-bigquery
  profiles:
    - default
    - cloud-tests-1
    - cloud-tests-2
- modules:
    - plugin/trino-cassandra
- modules:
    - plugin/trino-clickhouse
- modules:
    - plugin/trino-delta-lake
  profiles:
    - default
    - cloud-tests
    - fte-tests
- modules:
    - plugin/trino-druid
- modules:
    - plugin/trino-duckdb
- modules:
    - plugin/trino-elasticsearch
- modules:
    - plugin/trino-exchange-filesystem
  profiles:
    - default
    - cloud-tests
- modules:
    - plugin/trino-exasol
- modules:
    - plugin/trino-google-sheets
  profiles:
    - default
    - cloud-tests
- modules:
    - plugin/trino-hive
  profiles:
    - default
    - cloud-tests
    - fte-tests
    - test-parquet
- modules:
    - plugin/trino-hudi
- modules:
    - plugin/trino-iceberg
  profiles:
    - default
    - cloud-tests
    - fte-tests
    - floci-and-avro
- modules:
    - plugin/trino-ignite
- modules:
    - plugin/trino-kafka
- modules:
    - plugin/trino-lakehouse
- modules:
    - plugin/trino-mariadb
- modules:
    - plugin/trino-mongodb
- modules:
    - plugin/trino-mysql
- modules:
    - plugin/trino-opensearch
- modules:
    - plugin/trino-oracle
- modules:
    - plugin/trino-pinot
- modules:
    - plugin/trino-postgresql
- modules:
    - plugin/trino-redis
- modules:
    - plugin/trino-redshift
  profiles:
    - default
    - cloud-tests
    - fte-tests
- modules:
    - plugin/trino-resource-group-managers
- modules:
    - plugin/trino-singlestore
- modules:
    - plugin/trino-snowflake
  profiles:
    - default
    - cloud-tests
- modules:
    - plugin/trino-sqlserver
- modules:
    - testing/trino-faulttolerant-tests
  profiles:
    - default
    - test-fault-tolerant-delta
    - test-fault-tolerant-hive
    - test-fault-tolerant-iceberg
- modules:
    - testing/trino-tests
