# Install a YAML language server in your IDE to validate against the schema, or use a tool
# like https://github.com/yaml-schema/yaml-schema
# yaml-language-server: $schema=./schedule-config-schema.yml

- modules:
    - client/trino-jdbc
    - core/trino-spi
    - core/trino-web-ui
- modules:
    - plugin/trino-base-jdbc
    - plugin/trino-faker
    - plugin/trino-geospatial
    - plugin/trino-memory
    - plugin/trino-openlineage
    - plugin/trino-thrift
- modules:
    - lib/trino-orc
    - lib/trino-parquet
- modules:
    - lib/trino-filesystem
    - lib/trino-filesystem-azure
    - lib/trino-filesystem-gcs
    - lib/trino-filesystem-manager
    - lib/trino-filesystem-s3
    - lib/trino-hdfs
    - lib/trino-hive-formats
    - plugin/trino-blob-cache-alluxio
    - plugin/trino-blob-cache-memory
- { modules: core/trino-main }
- { modules: lib/trino-filesystem-azure, profile: cloud-tests }
- { modules: lib/trino-filesystem-gcs, profile: cloud-tests }
- { modules: lib/trino-filesystem-s3, profile: cloud-tests }
- { modules: plugin/trino-bigquery }
- { modules: plugin/trino-bigquery, profile: cloud-tests-2 }
- { modules: plugin/trino-cassandra }
- { modules: plugin/trino-clickhouse }
- { modules: plugin/trino-delta-lake }
- { modules: plugin/trino-delta-lake, profile: cloud-tests }
- { modules: plugin/trino-delta-lake, profile: fte-tests }
- { modules: plugin/trino-druid }
- { modules: plugin/trino-duckdb }
- { modules: plugin/trino-elasticsearch }
- { modules: plugin/trino-exchange-filesystem, profile: cloud-tests }
- { modules: plugin/trino-exasol }
- { modules: plugin/trino-google-sheets }
- { modules: plugin/trino-google-sheets, profile: cloud-tests }
- { modules: plugin/trino-hive }
- { modules: plugin/trino-hive, profile: cloud-tests }
- { modules: plugin/trino-hive, profile: fte-tests }
- { modules: plugin/trino-hive, profile: test-parquet }
- { modules: plugin/trino-hudi }
- { modules: plugin/trino-iceberg }
- { modules: plugin/trino-iceberg, profile: cloud-tests }
- { modules: plugin/trino-iceberg, profile: fte-tests }
- { modules: plugin/trino-iceberg, profile: floci-and-avro }
- { modules: plugin/trino-ignite }
- { modules: plugin/trino-kafka }
- { modules: plugin/trino-lakehouse }
- { modules: plugin/trino-mariadb }
- { modules: plugin/trino-mongodb }
- { modules: plugin/trino-mysql }
- { modules: plugin/trino-opensearch }
- { modules: plugin/trino-oracle }
- { modules: plugin/trino-pinot }
- { modules: plugin/trino-postgresql }
- { modules: plugin/trino-redis }
- { modules: plugin/trino-redshift }
- { modules: plugin/trino-redshift, profile: cloud-tests }
- { modules: plugin/trino-redshift, profile: fte-tests }
- { modules: plugin/trino-resource-group-managers }
- { modules: plugin/trino-singlestore }
- { modules: plugin/trino-snowflake }
# TODO re-enable Snowflake cloud tests https://github.com/trinodb/trino/issues/30823
# - { modules: plugin/trino-snowflake, profile: cloud-tests }
- { modules: plugin/trino-sqlserver }
- { modules: plugin/trino-trino }
- { modules: testing/trino-faulttolerant-tests, profile: default }
- { modules: testing/trino-faulttolerant-tests, profile: test-fault-tolerant-delta }
- { modules: testing/trino-faulttolerant-tests, profile: test-fault-tolerant-hive }
- { modules: testing/trino-faulttolerant-tests, profile: test-fault-tolerant-iceberg }
- { modules: testing/trino-tests }
