/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.spi.connector;

import io.airlift.slice.Slice;
import io.trino.instrumentation.events.ConnectorPageSinkEvent;
import io.trino.spi.Page;

import java.util.Collection;
import java.util.concurrent.CompletableFuture;

import static java.util.Objects.requireNonNull;

/**
 * This class has been generated by the InstrumentationGenerator class.
 * The generation is a one-time event and is not repeated during build.
 */
@SuppressWarnings({"DeprecatedApi", "ExperimentalSpi", "DuplicatedCode"})
public final class InstrumentedConnectorPageSink
        implements ConnectorPageSink
{
    private final String catalogName;

    private final String delegateClassName;

    private final ConnectorPageSink delegate;

    private InstrumentedConnectorPageSink(String catalogName, ConnectorPageSink delegate)
    {
        this.catalogName = requireNonNull(catalogName, "catalogName is null");
        this.delegate = requireNonNull(delegate, "delegate is null");
        this.delegateClassName = delegate.getClass().getSimpleName();
    }

    public static ConnectorPageSink instrument(ConnectorPageSink delegate)
    {
        if (delegate instanceof InstrumentedConnectorPageSink instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorPageSink("unknown", delegate);
    }

    public static ConnectorPageSink instrument(String catalogName, ConnectorPageSink delegate)
    {
        if (delegate instanceof InstrumentedConnectorPageSink instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorPageSink(catalogName, delegate);
    }

    @Override
    public CompletableFuture<Collection<Slice>> finish()
    {
        final ConnectorPageSinkEvent event = new ConnectorPageSinkEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "finish";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.finish();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }

    @Override
    public void abort()
    {
        final ConnectorPageSinkEvent event = new ConnectorPageSinkEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "abort";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            delegate.abort();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }

    @Override
    public CompletableFuture<?> appendPage(Page page)
    {
        final ConnectorPageSinkEvent event = new ConnectorPageSinkEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "appendPage";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.appendPage(page);
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }

    @Override
    public long getCompletedBytes()
    {
        final ConnectorPageSinkEvent event = new ConnectorPageSinkEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "getCompletedBytes";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.getCompletedBytes();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }

    @Override
    public long getMemoryUsage()
    {
        final ConnectorPageSinkEvent event = new ConnectorPageSinkEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "getMemoryUsage";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.getMemoryUsage();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }

    @Override
    public long getValidationCpuNanos()
    {
        final ConnectorPageSinkEvent event = new ConnectorPageSinkEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "getValidationCpuNanos";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.getValidationCpuNanos();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }
}
