/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.spi.connector;

import io.trino.instrumentation.events.ConnectorPageSinkProviderEvent;

import static java.util.Objects.requireNonNull;

/**
 * This class has been generated by the InstrumentationGenerator class.
 * The generation is a one-time event and is not repeated during build.
 */
@SuppressWarnings({"DeprecatedApi", "ExperimentalSpi", "DuplicatedCode"})
public final class InstrumentedConnectorPageSinkProvider
        implements ConnectorPageSinkProvider
{
    private final String catalogName;

    private final String delegateClassName;

    private final ConnectorPageSinkProvider delegate;

    private InstrumentedConnectorPageSinkProvider(String catalogName,
                                                  ConnectorPageSinkProvider delegate)
    {
        this.catalogName = requireNonNull(catalogName, "catalogName is null");
        this.delegate = requireNonNull(delegate, "delegate is null");
        this.delegateClassName = delegate.getClass().getSimpleName();
    }

    public static ConnectorPageSinkProvider instrument(ConnectorPageSinkProvider delegate)
    {
        if (delegate instanceof InstrumentedConnectorPageSinkProvider instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorPageSinkProvider("unknown", delegate);
    }

    public static ConnectorPageSinkProvider instrument(String catalogName,
                                                       ConnectorPageSinkProvider delegate)
    {
        if (delegate instanceof InstrumentedConnectorPageSinkProvider instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorPageSinkProvider(catalogName, delegate);
    }

    @Override
    public ConnectorPageSink createPageSink(ConnectorTransactionHandle transactionHandle,
                                            ConnectorSession session, ConnectorTableExecuteHandle tableExecuteHandle,
                                            ConnectorPageSinkId pageSinkId)
    {
        final ConnectorPageSinkProviderEvent event = new ConnectorPageSinkProviderEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "createPageSink";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return io.trino.spi.connector.InstrumentedConnectorPageSink.instrument(catalogName, delegate.createPageSink(transactionHandle, session, tableExecuteHandle, pageSinkId));
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.queryId = session.getQueryId();
                event.commit();
            }
        }
    }

    @Override
    public ConnectorPageSink createPageSink(ConnectorTransactionHandle transactionHandle,
                                            ConnectorSession session, ConnectorInsertTableHandle insertTableHandle,
                                            ConnectorPageSinkId pageSinkId)
    {
        final ConnectorPageSinkProviderEvent event = new ConnectorPageSinkProviderEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "createPageSink";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return io.trino.spi.connector.InstrumentedConnectorPageSink.instrument(catalogName, delegate.createPageSink(transactionHandle, session, insertTableHandle, pageSinkId));
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.queryId = session.getQueryId();
                event.commit();
            }
        }
    }

    @Override
    public ConnectorPageSink createPageSink(ConnectorTransactionHandle transactionHandle,
                                            ConnectorSession session, ConnectorOutputTableHandle outputTableHandle,
                                            ConnectorPageSinkId pageSinkId)
    {
        final ConnectorPageSinkProviderEvent event = new ConnectorPageSinkProviderEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "createPageSink";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return io.trino.spi.connector.InstrumentedConnectorPageSink.instrument(catalogName, delegate.createPageSink(transactionHandle, session, outputTableHandle, pageSinkId));
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.queryId = session.getQueryId();
                event.commit();
            }
        }
    }

    @Override
    public ConnectorMergeSink createMergeSink(ConnectorTransactionHandle transactionHandle,
                                              ConnectorSession session, ConnectorMergeTableHandle mergeHandle,
                                              ConnectorPageSinkId pageSinkId)
    {
        final ConnectorPageSinkProviderEvent event = new ConnectorPageSinkProviderEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "createMergeSink";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.createMergeSink(transactionHandle, session, mergeHandle, pageSinkId);
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.queryId = session.getQueryId();
                event.commit();
            }
        }
    }
}
