/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.spi.connector;

import io.trino.instrumentation.events.RecordSetEvent;
import io.trino.spi.type.Type;

import java.util.List;

import static java.util.Objects.requireNonNull;

/**
 * This class has been generated by the InstrumentationGenerator class.
 * The generation is a one-time event and is not repeated during build.
 */
@SuppressWarnings({"DeprecatedApi", "ExperimentalSpi", "DuplicatedCode"})
public final class InstrumentedRecordSet
        implements RecordSet
{
    private final String catalogName;

    private final String delegateClassName;

    private final RecordSet delegate;

    private InstrumentedRecordSet(String catalogName, RecordSet delegate)
    {
        this.catalogName = requireNonNull(catalogName, "catalogName is null");
        this.delegate = requireNonNull(delegate, "delegate is null");
        this.delegateClassName = delegate.getClass().getSimpleName();
    }

    public static RecordSet instrument(RecordSet delegate)
    {
        if (delegate instanceof InstrumentedRecordSet instrumented) {
            return instrumented;
        }
        return new InstrumentedRecordSet("unknown", delegate);
    }

    public static RecordSet instrument(String catalogName, RecordSet delegate)
    {
        if (delegate instanceof InstrumentedRecordSet instrumented) {
            return instrumented;
        }
        return new InstrumentedRecordSet(catalogName, delegate);
    }

    @Override
    public RecordCursor cursor()
    {
        final RecordSetEvent event = new RecordSetEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "cursor";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.cursor();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }

    @Override
    public List<Type> getColumnTypes()
    {
        final RecordSetEvent event = new RecordSetEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "getColumnTypes";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.getColumnTypes();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }
}
