/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.spi.connector;

import io.trino.instrumentation.events.ConnectorPageSourceProviderEvent;

import java.util.List;

import static java.util.Objects.requireNonNull;

/**
 * This class has been generated by the InstrumentationGenerator class.
 * The generation is a one-time event and is not repeated during build.
 */
@SuppressWarnings({"DeprecatedApi", "ExperimentalSpi", "DuplicatedCode"})
public final class InstrumentedConnectorPageSourceProvider
        implements ConnectorPageSourceProvider
{
    private final String catalogName;

    private final String delegateClassName;

    private final ConnectorPageSourceProvider delegate;

    private InstrumentedConnectorPageSourceProvider(String catalogName,
                                                    ConnectorPageSourceProvider delegate)
    {
        this.catalogName = requireNonNull(catalogName, "catalogName is null");
        this.delegate = requireNonNull(delegate, "delegate is null");
        this.delegateClassName = delegate.getClass().getSimpleName();
    }

    public static ConnectorPageSourceProvider instrument(ConnectorPageSourceProvider delegate)
    {
        if (delegate instanceof InstrumentedConnectorPageSourceProvider instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorPageSourceProvider("unknown", delegate);
    }

    public static ConnectorPageSourceProvider instrument(String catalogName,
                                                         ConnectorPageSourceProvider delegate)
    {
        if (delegate instanceof InstrumentedConnectorPageSourceProvider instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorPageSourceProvider(catalogName, delegate);
    }

    @Override
    public ConnectorPageSource createPageSource(ConnectorTransactionHandle transaction,
                                                ConnectorSession session, ConnectorSplit split, ConnectorTableHandle table,
                                                List<ColumnHandle> columns, DynamicFilter dynamicFilter)
    {
        final ConnectorPageSourceProviderEvent event = new ConnectorPageSourceProviderEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "createPageSource";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return io.trino.spi.connector.InstrumentedConnectorPageSource.instrument(catalogName, delegate.createPageSource(transaction, session, split, table, columns, dynamicFilter));
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.queryId = session.getQueryId();
                event.commit();
            }
        }
    }
}
