/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.spi.connector;

import io.trino.instrumentation.events.ConnectorFactoryEvent;

import java.util.Map;

import static java.util.Objects.requireNonNull;

/**
 * This class has been generated by the InstrumentationGenerator class.
 * The generation is a one-time event and is not repeated during build.
 */
@SuppressWarnings({"DeprecatedApi", "ExperimentalSpi", "DuplicatedCode"})
public final class InstrumentedConnectorFactory
        implements ConnectorFactory
{
    private final String catalogName;

    private final String delegateClassName;

    private final ConnectorFactory delegate;

    private InstrumentedConnectorFactory(String catalogName, ConnectorFactory delegate)
    {
        this.catalogName = requireNonNull(catalogName, "catalogName is null");
        this.delegate = requireNonNull(delegate, "delegate is null");
        this.delegateClassName = delegate.getClass().getSimpleName();
    }

    public static ConnectorFactory instrument(ConnectorFactory delegate)
    {
        if (delegate instanceof InstrumentedConnectorFactory instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorFactory("unknown", delegate);
    }

    public static ConnectorFactory instrument(String catalogName, ConnectorFactory delegate)
    {
        if (delegate instanceof InstrumentedConnectorFactory instrumented) {
            return instrumented;
        }
        return new InstrumentedConnectorFactory(catalogName, delegate);
    }

    @Override
    public String getName()
    {
        final ConnectorFactoryEvent event = new ConnectorFactoryEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "getName";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return delegate.getName();
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }

    @Override
    public Connector create(String catalogName, Map<String, String> config,
                            ConnectorContext context)
    {
        final ConnectorFactoryEvent event = new ConnectorFactoryEvent();
        if (event.isEnabled()) {
            event.className = delegateClassName;
            event.method = "create";
            event.catalogName = catalogName;
        }
        event.begin();
        try {
            return io.trino.spi.connector.InstrumentedConnector.instrument(catalogName, delegate.create(catalogName, config, context));
        }
        finally {
            event.end();
            if (event.shouldCommit()) {
                event.commit();
            }
        }
    }
}
