/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.plugin.jdbc;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableSet;
import com.google.errorprone.annotations.concurrent.GuardedBy;
import io.airlift.log.Logger;
import io.trino.spi.connector.ColumnHandle;
import io.trino.spi.connector.ConnectorSession;
import io.trino.spi.connector.ConnectorSplit;
import io.trino.spi.connector.ConnectorSplitManager;
import io.trino.spi.connector.ConnectorSplitSource;
import io.trino.spi.connector.ConnectorTransactionHandle;
import io.trino.spi.connector.Constraint;
import io.trino.spi.connector.DynamicFilterSnapshot;
import io.trino.spi.connector.FixedSplitSource;
import io.trino.spi.predicate.TupleDomain;

import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

import static com.google.common.base.Verify.verify;
import static com.google.common.collect.ImmutableList.toImmutableList;
import static io.trino.plugin.jdbc.JdbcDynamicFilteringSessionProperties.getDynamicFilteringWaitTimeout;
import static java.util.Objects.requireNonNull;

/**
 * Attaches dynamic filter to {@link JdbcSplit} after {@link JdbcDynamicFilteringSplitManager}
 * has waited for the collection of dynamic filters.
 * This allows JDBC based connectors to avoid waiting for dynamic filters again on the worker node
 * in {@link JdbcPageSourceProvider}. The number of splits generated by JDBC based connectors are
 * typically small, therefore attaching dynamic filter here does not add significant overhead.
 * Waiting for dynamic filters in {@link JdbcDynamicFilteringSplitManager} is preferred over waiting
 * for them on the worker node in {@link JdbcPageSourceProvider} to allow connectors to take advantage of
 * dynamic filters during the splits generation phase.
 */
public class DynamicFilteringJdbcSplitSource
        implements ConnectorSplitSource
{
    private static final Logger log = Logger.get(DynamicFilteringJdbcSplitSource.class);

    private final ConnectorSplitManager delegateSplitManager;
    private final ConnectorTransactionHandle transaction;
    private final ConnectorSession session;
    private final JdbcTableHandle table;
    private final Set<ColumnHandle> dynamicFilterColumns;
    private final Constraint constraint;
    private final long dynamicFilteringTimeoutMillis;

    @GuardedBy("this")
    private Optional<ConnectorSplitSource> delegateSplitSource = Optional.empty();

    DynamicFilteringJdbcSplitSource(
            ConnectorSplitManager delegateSplitManager,
            ConnectorTransactionHandle transaction,
            ConnectorSession session,
            JdbcTableHandle table,
            Set<ColumnHandle> dynamicFilterColumns,
            Constraint constraint)
    {
        this.delegateSplitManager = requireNonNull(delegateSplitManager, "delegateSplitManager is null");
        this.transaction = requireNonNull(transaction, "transaction is null");
        this.session = requireNonNull(session, "session is null");
        this.table = requireNonNull(table, "table is null");
        this.dynamicFilterColumns = ImmutableSet.copyOf(dynamicFilterColumns);
        this.constraint = requireNonNull(constraint, "constraint is null");
        this.dynamicFilteringTimeoutMillis = getDynamicFilteringWaitTimeout(session).toMillis();
    }

    @Override
    public long getRequestedDynamicFilterWaitTimeoutMillis()
    {
        return dynamicFilteringTimeoutMillis;
    }

    @Override
    public CompletableFuture<List<ConnectorSplit>> getNextBatch(int maxSize, DynamicFilterSnapshot dynamicFilterSnapshot)
    {
        log.debug(
                "Enumerating splits (query %s, table: %s, completed: %s)",
                session.getQueryId(),
                table,
                dynamicFilterSnapshot.isComplete());
        TupleDomain<JdbcColumnHandle> dynamicFilterPredicate = dynamicFilterSnapshot.currentPredicate()
                .transformKeys(JdbcColumnHandle.class::cast);
        return getDelegateSplitSource(dynamicFilterSnapshot).getNextBatch(maxSize, dynamicFilterSnapshot)
                .thenApply(splits -> splits.stream()
                        // attach dynamic filter constraint to JdbcSplit
                        .map(split -> {
                            JdbcSplit jdbcSplit = (JdbcSplit) split;
                            // If split was a subclass of JdbcSplit, there would be additional information
                            // that we would need to pass further on.
                            verify(jdbcSplit.getClass() == JdbcSplit.class, "Unexpected split type %s", jdbcSplit);
                            return (ConnectorSplit) jdbcSplit.withDynamicFilter(dynamicFilterPredicate);
                        })
                        .collect(toImmutableList()));
    }

    @Override
    public void close()
    {
        getOptionalDelegateSplitSource().ifPresent(ConnectorSplitSource::close);
    }

    @Override
    public boolean isFinished()
    {
        return getOptionalDelegateSplitSource()
                .map(ConnectorSplitSource::isFinished)
                .orElse(false);
    }

    private synchronized ConnectorSplitSource getDelegateSplitSource(DynamicFilterSnapshot dynamicFilterSnapshot)
    {
        if (delegateSplitSource.isPresent()) {
            return delegateSplitSource.get();
        }

        JdbcTableHandle intersected = table.intersectedWithConstraint(dynamicFilterSnapshot.currentPredicate());
        if (intersected.getConstraint().isNone()) {
            delegateSplitSource = Optional.of(new FixedSplitSource(ImmutableList.of()));
            return delegateSplitSource.get();
        }

        delegateSplitSource = Optional.of(delegateSplitManager.getSplits(
                transaction,
                session,
                intersected,
                dynamicFilterColumns,
                constraint));
        return delegateSplitSource.get();
    }

    private synchronized Optional<ConnectorSplitSource> getOptionalDelegateSplitSource()
    {
        return delegateSplitSource;
    }
}
