wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repository.apache.org/content/repositories/maven-2450/org/apache/maven/apache-maven/4.0.0-rc-6/apache-maven-4.0.0-rc-6-bin.zip
