version: '2'
services:

    presto-master:
        volumes:
            - keytabs:/etc/presto/conf/
            - ../../../conf/docker/two-kerberos-hives/presto-master/etc/krb5.conf:/etc/krb5.conf
            - ../../../conf/docker/two-kerberos-hives/presto-master/etc/presto/auth_to_local.xml:/etc/presto/auth_to_local.xml
            - ../../../conf/docker/two-kerberos-hives/presto-master/etc/presto/hive1.properties:/docker/volumes/conf/presto/etc/catalog/hive1.properties
            - ../../../conf/docker/two-kerberos-hives/presto-master/etc/presto/hive2.properties:/docker/volumes/conf/presto/etc/catalog/hive2.properties

    hadoop-master:
        volumes:
            - keytabs:/presto_keytabs
            - ../../../conf/docker/two-kerberos-hives/hadoop-master/entrypoint.sh:/entrypoint.sh
        entrypoint: sh /entrypoint.sh

    hadoop-master-2:
        extends:
            service: java-8-base
        image: '${HADOOP_BASE_IMAGE}-kerberized-2:${DOCKER_IMAGES_VERSION}'
        hostname: hadoop-master-2
        volumes:
            - keytabs:/presto_keytabs
            - ../../../conf/docker/two-kerberos-hives/hadoop-master-2/entrypoint.sh:/entrypoint.sh
        entrypoint: sh /entrypoint.sh

volumes:
    keytabs:
