name: compile-commit
description: "Compile currently checked out commit"
inputs:
  base_ref:
    description: 'Git base ref'

runs:
  using: composite
  steps:
    - name: Get the hash of the tree at HEAD
      id: repo-hash
      shell: bash
      run: |
        TREE_HASH=$( git rev-parse HEAD: )
        echo "tree-hash=${TREE_HASH}" >> $GITHUB_OUTPUT
    - name: Cache compile-commit action success
      id: check-compile-commit-success
      uses: actions/cache@v3
      with:
        path: compile-commit-success.txt
        # use tree hashes instead of commit hashes to reuse cache when changes in commits are reorganized without changing the workspace
        key: compile-commit-success-${{ github.event.pull_request.head.repo.full_name }}-${{ steps.repo-hash.outputs.tree-hash }}
    - uses: ./.github/actions/setup
      if: steps.check-compile-commit-success.outputs.cache-hit != 'true'
      with:
        # Dependencies are downloaded explicitly below, after MAVEN has been set here. This allows modifications to the MAVEN setup with a PR.
        download_dependencies: false
    - name: Check if a specified commit compiles
      shell: bash
      if: steps.check-compile-commit-success.outputs.cache-hit != 'true'
      run: |
        set -x

        # The section below should always contain copies of env variables from .github/workflows/ci.yml to maintain both files in sync
        # It's important that these values are NOT passed as parameters, because then their values would always be taken from PR HEAD
        # -------
        # allow overriding Maven command
        export MAVEN="./mvnw --offline"
        # maven.wagon.rto is in millis, defaults to 30m
        MAVEN_INSTALL_OPTS="-Xmx3G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
        MAVEN_COMPILE_COMMITS="-B --strict-checksums --quiet -T 1C -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all=true -Dmaven.javadoc.skip=true --no-snapshot-updates --no-transfer-progress -pl !:trino-server-rpm"
        export MAVEN_GIB="-P gib -Dgib.referenceBranch=refs/remotes/origin/${{ inputs.base_ref }}"
        RETRY=.github/bin/retry
        # -------

        # For building with Maven we need MAVEN_OPTS to equal MAVEN_INSTALL_OPTS
        export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
        ./.github/bin/download-maven-dependencies.sh
        $MAVEN package \
          ${MAVEN_COMPILE_COMMITS} `# defaults, kept in sync with ci.yml` \
          -Dair.check.skip-all=false -Dair.check.skip-basic=true -Dair.check.skip-extended=true -Dair.check.skip-checkstyle=false \
          ${MAVEN_GIB}
    - name: Mark this workspace as successfully compiled
      if: steps.check-compile-commit-success.outputs.cache-hit != 'true'
      shell: bash
      run: echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" > compile-commit-success.txt
    - name: Clean local Maven repo
      # Avoid creating a cache entry because this job doesn't download all dependencies
      if: steps.check-compile-commit-success.outputs.cache-hit != 'true' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: rm -rf ~/.m2/repository
