name: compile-commit
description: "Compile currently checked out commit"
inputs:
  base_ref:
    description: 'Git base ref'

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup
    - name: Check if a specified commit compiles
      shell: bash
      run: |
        set -x

        # The section below should always contain copies of env variables from .github/workflows/ci.yml to maintain both files in sync
        # It's important that these values are NOT passed as parameters, because then their values would always be taken from PR HEAD
        # -------
        # allow overriding Maven command
        MAVEN="./mvnw"
        # maven.wagon.rto is in millis, defaults to 30m
        MAVEN_INSTALL_OPTS="-Xmx3G -XX:+ExitOnOutOfMemoryError -Dmaven.wagon.rto=60000"
        MAVEN_COMPILE_COMMITS="-B --strict-checksums --quiet -T C1 -DskipTests -Dmaven.source.skip=true -Dair.check.skip-all=true -Dmaven.javadoc.skip=true --no-snapshot-updates --no-transfer-progress -pl !:trino-server-rpm"
        MAVEN_GIB="-P gib -Dgib.referenceBranch=refs/remotes/origin/${{ inputs.base_ref }}"
        RETRY=.github/bin/retry
        # -------

        # For building with Maven we need MAVEN_OPTS to equal MAVEN_INSTALL_OPTS
        export MAVEN_OPTS="${MAVEN_INSTALL_OPTS}"
        $RETRY $MAVEN dependency:go-offline
        $MAVEN package \
          ${MAVEN_COMPILE_COMMITS} `# defaults, kept in sync with ci.yml` \
          -Dair.check.skip-all=false -Dair.check.skip-basic=true -Dair.check.skip-extended=true -Dair.check.skip-checkstyle=false \
          ${MAVEN_GIB}
    - name: Clean local Maven repo
      # Avoid creating a cache entry because this job doesn't download all dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: rm -rf ~/.m2/repository
