SELECT nvl(t2.hdid,t1.hdid) AS hdid,
       nvl(t2.uid,t1.uid) AS UID,
       nvl(t2.deviceid,t1.deviceid) AS deviceid,
       nvl(t2.os,t1.os) AS os,
       nvl(t2.os_version,t1.os_version) AS os_version,
       nvl(t2.imei,t1.imei) AS imei,
       nvl(t2.imsi,t1.imsi) AS imsi,
       nvl(t2.client_version,t1.client_version) AS client_version,
       nvl(t2.tz,t1.tz) AS tz,
       nvl(t2.locale,t1.locale) AS locale,
       nvl(t2.country,t1.country) AS country,
       nvl(t2.resolution,t2.resolution) AS resolution,
       nvl(t2.dpi,t1.dpi) AS dpi,
       nvl(t2.isp,t1.isp) AS isp,
       nvl(t1.channel,t2.channel) AS channel,
       nvl(t2.model,t1.model) AS model,
       nvl(t2.vendor,t1.vendor) AS vendor,
       nvl(t2.sdk_version,t1.sdk_version) AS sdk_version,
       nvl(t2.appkey,t1.appkey) AS appkey,
       nvl(t2.guid,t1.guid) AS guid,
       nvl(t2.mac,t1.mac) AS mac,
       nvl(t2.debug,t1.debug) AS debug,
       nvl(t2.gaid,t1.gaid) AS gaid,
       nvl(t2.idfa,t1.idfa) AS idfa,
       nvl(t2.rtime,t1.rtime) AS rtime,
       nvl(t2.ip,t1.ip) AS ip,
       nvl(t2.login_state,t1.login_state) AS login_state,
       nvl(t2.net,t1.net) AS net,
       nvl(t2.lng,t1.lng) AS lng,
       nvl(t2.lat,t1.lat) AS lat,
       nvl(t2.market_source,t1.market_source) AS market_source,
       nvl(t2.appsflyerid,t1.appsflyerid) AS appsflyerid,
       nvl(t2.af_attribution_type,t1.af_attribution_type) AS af_attribution_type,
       nvl(t2.af_click_time,t1.af_click_time) AS af_click_time,
       nvl(t2.af_download_time,t1.af_download_time) AS af_download_time,
       nvl(t2.af_install_time,t1.af_install_time) AS af_install_time,
       nvl(t2.af_media_source,t1.af_media_source) AS af_media_source,
       nvl(t2.af_agency,t1.af_agency) AS af_agency,
       nvl(t2.af_channel,t1.af_channel) AS af_channel,
       nvl(t2.af_keywords,t1.af_keywords) AS af_keywords,
       nvl(t2.af_campaign,t1.af_campaign) AS af_campaign,
       nvl(t2.af_c_id,t1.af_c_id) AS af_c_id,
       nvl(t2.af_adset,t1.af_adset) AS af_adset,
       nvl(t2.af_adset_id,t1.af_adset_id) AS af_adset_id,
       nvl(t2.af_ad,t1.af_ad) AS af_ad,
       nvl(t2.af_ad_id,t1.af_ad_id) AS af_ad_id,
       nvl(t2.af_fb_campaign_name,t1.af_fb_campaign_name) AS af_fb_campaign_name,
       nvl(t2.af_fb_campaign_id,t1.af_fb_campaign_id) AS af_fb_campaign_id,
       nvl(t2.af_fb_adset_name,t1.af_fb_adset_name) AS af_fb_adset_name,
       nvl(t2.af_fb_adset_id,t1.af_fb_adset_id) AS af_fb_adset_id,
       nvl(t2.af_fb_adgroup_name,t1.af_fb_adgroup_name) AS af_fb_adgroup_name,
       nvl(t2.af_fb_adgroup_id,t1.af_fb_adgroup_id) AS af_fb_adgroup_id,
       nvl(t2.af_ad_type,t1.af_ad_type) AS af_ad_type,
       nvl(t2.af_siteid,t1.af_siteid) AS af_siteid,
       nvl(t2.af_sub1,t1.af_sub1) AS af_sub1,
       nvl(t2.af_sub2,t1.af_sub2) AS af_sub2,
       nvl(t2.af_sub3,t1.af_sub3) AS af_sub3,
       nvl(t2.af_sub4,t1.af_sub4) AS af_sub4,
       nvl(t2.af_sub5,t1.af_sub5) AS af_sub5,
       nvl(t2.af_http_referrer,t1.af_http_referrer) AS af_http_referrer,
       nvl(t2.af_click_url,t1.af_click_url) AS af_click_url,
       nvl(t2.af_cost_model,t1.af_cost_model) AS af_cost_model,
       nvl(t2.af_cost_value,t1.af_cost_value) AS af_cost_value,
       nvl(t2.af_cost_currency,t1.af_cost_currency) AS af_cost_currency,
       nvl(t2.af_cost_per_install,t1.af_cost_per_install) AS af_cost_per_install,
       nvl(t2.af_is_retargeting,t1.af_is_retargeting) AS af_is_retargeting,
       nvl(t2.af_re_targeting_conversion_type,t1.af_re_targeting_conversion_type) AS af_re_targeting_conversion_type,
       nvl(t2.af_country_code,t1.af_country_code) AS af_country_code,
       nvl(t2.af_city,t1.af_city) AS af_city,
       nvl(t2.af_ip,t1.af_ip) AS af_ip,
       nvl(t2.af_wifi,t1.af_wifi) AS af_wifi,
       nvl(t2.af_mac,t1.af_mac) AS af_mac,
       nvl(t2.af_operator,t1.af_operator) AS af_operator,
       nvl(t2.af_carrier,t1.af_carrier) AS af_carrier,
       nvl(t2.af_language,t1.af_language) AS af_language,
       nvl(t2.af_advertising_id,t1.af_advertising_id) AS af_advertising_id,
       nvl(t2.af_android_id,t1.af_android_id) AS af_android_id,
       nvl(t2.af_customer_user_id,t1.af_customer_user_id) AS af_customer_user_id,
       nvl(t2.af_imei,t1.af_imei) AS af_imei,
       nvl(t2.af_platform,t1.af_platform) AS af_platform,
       nvl(t2.af_device_brand,t1.af_device_brand) AS af_device_brand,
       nvl(t2.af_device_model,t1.af_device_model) AS af_device_model,
       nvl(t2.af_os_version,t1.af_os_version) AS af_os_version,
       nvl(t2.af_app_version,t1.af_app_version) AS af_app_version,
       nvl(t2.af_sdk_version,t1.af_sdk_version) AS af_sdk_version,
       nvl(t2.af_app_id,t1.af_app_id) AS af_app_id,
       nvl(t2.af_app_name,t1.af_app_name) AS af_app_name,
       nvl(t2.af_event_time,t1.af_event_time) AS af_event_time,
       nvl(t2.af_event_name,t1.af_event_name) AS af_event_name,
       nvl(t2.af_event_value,t1.af_event_value) AS af_event_value,
       nvl(t2.af_currency,t1.af_currency) AS af_currency,
       nvl(t2.af_validated,t1.af_validated) AS af_validated,
       nvl(t2.af_download_time_selected_timezone,t1.af_download_time_selected_timezone) AS af_download_time_selected_timezone,
       nvl(t2.af_click_time_selected_timezone,t1.af_click_time_selected_timezone) AS af_click_time_selected_timezone,
       nvl(t2.af_install_time_selected_timezone,t1.af_install_time_selected_timezone) AS af_install_time_selected_timezone,
       nvl(t2.af_event_time_selected_timezone,t1.af_event_time_selected_timezone) AS af_event_time_selected_timezone,
       nvl(t2.af_selected_currency,t1.af_selected_currency) AS af_selected_currency,
       nvl(t2.af_revenue_in_selected_currency,t1.af_revenue_in_selected_currency) AS af_revenue_in_selected_currency,
       nvl(t2.af_cost_in_selected_currency,t1.af_cost_in_selected_currency) AS af_cost_in_selected_currency,
       nvl(t2.af_idfa,t1.af_idfa) AS af_idfa,
       nvl(t2.af_from_postid,t1.af_from_postid) AS af_from_postid,
       nvl(t2.af_from_uid,t1.af_from_uid) AS af_from_uid,
       combine(t1.user_map,t2.user_map) AS user_map,
       nvl(t1.hdid_install_date,t2.hdid_install_date) AS hdid_install_date,
       nvl(t1.hdid_country,t2.hdid_country) AS hdid_country,
       nvl(t2.notification_enabled,t1.notification_enabled) AS notification_enabled,
       if(t2.hdid IS NOT NULL,'2019-07-24',t1.last_active_date) AS last_active_date,
       nvl(t1.first_active_date,'2019-07-24') AS first_active_date,
       if(t2.uid IS NOT NULL,combine(t1.active_user_map,map('2019-07-24',t2.uid)),t1.active_user_map) AS active_user_map,
       if(t2.lat!=0
          AND t2.lng!=0,combine(t1.active_lbs_map,map('2019-07-24',concat(t2.lat,',',t2.lng))),t1.active_lbs_map) AS active_lbs_map,
       if(t2.hdid IS NULL
          AND datediff('2019-07-24',t1.last_active_date)=7,if(t1.d7_loss_array IS NULL,array('2019-07-24'),append(t1.d7_loss_array,'2019-07-24')),t1.d7_loss_array) AS d7_loss_array,
       if(t2.hdid IS NULL
          AND datediff('2019-07-24',t1.last_active_date)=14,if(t1.d14_loss_array IS NULL,array('2019-07-24'),append(t1.d14_loss_array,'2019-07-24')),t1.d14_loss_array) AS d14_loss_array,
       if(t2.hdid IS NULL
          AND datediff('2019-07-24',t1.last_active_date)=30,if(t1.d30_loss_array IS NULL,array('2019-07-24'),append(t1.d30_loss_array,'2019-07-24')),t1.d30_loss_array) AS d30_loss_array,
       if(t2.hdid IS NULL
          AND datediff('2019-07-24',t1.last_active_date)=90,if(t1.d90_loss_array IS NULL,array('2019-07-24'),append(t1.d90_loss_array,'2019-07-24')),t1.d90_loss_array) AS d90_loss_array,
       if(t2.hdid IS NOT NULL
          AND t1.hdid IS NOT NULL
          AND datediff('2019-07-24',t1.last_active_date)>=7,if(t1.d7_back_array IS NULL,array('2019-07-24'),append(t1.d7_back_array,'2019-07-24')),t1.d7_back_array) AS d7_back_array,
       if(t2.hdid IS NOT NULL
          AND t1.hdid IS NOT NULL
          AND datediff('2019-07-24',t1.last_active_date)>=14,if(t1.d14_back_array IS NULL,array('2019-07-24'),append(t1.d14_back_array,'2019-07-24')),t1.d14_back_array) AS d14_back_array,
       if(t2.hdid IS NOT NULL
          AND t1.hdid IS NOT NULL
          AND datediff('2019-07-24',t1.last_active_date)>=30,if(t1.d30_back_array IS NULL,array('2019-07-24'),append(t1.d30_back_array,'2019-07-24')),t1.d30_back_array) AS d30_back_array,
       if(t2.hdid IS NOT NULL
          AND t1.hdid IS NOT NULL
          AND datediff('2019-07-24',t1.last_active_date)>=90,if(t1.d90_back_array IS NULL,array('2019-07-24'),append(t1.d90_back_array,'2019-07-24')),t1.d90_back_array) AS d90_back_array
FROM
  (SELECT *
   FROM mediate_tb.like_device_info_orc
   WHERE DAY='2019-07-23'
     AND hdid IS NOT NULL
     AND hdid !=''
     AND hdid NOT rlike '[^A-Za-z0-9]')t1
FULL OUTER JOIN
  (SELECT *
   FROM tmp.like_device_info_day
   WHERE DAY='2019-07-24'
     AND hdid NOT rlike '[^A-Za-z0-9]')t2 ON t1.hdid=t2.hdid