SELECT t1.hdid,
       nvl(session_cnt,0),
       nvl(use_time,0),
       nvl(version_cnt,0),
       nvl(video_click_count_1d,0),
       nvl(video_slide_count_1d,0),
       nvl(video_view_count_1d,0),
       nvl(video_view_valid_count_1d,0),
       nvl(video_view_time_1d,0),
       nvl(video_view_finish_count_1d,0),
       nvl(video_click_count_1d_hot,0),
       nvl(video_slide_count_1d_hot,0),
       nvl(video_view_count_1d_hot,0),
       nvl(video_view_valid_count_1d_hot,0),
       nvl(video_view_time_1d_hot,0),
       nvl(video_view_finish_count_1d_hot,0),
       nvl(video_click_count_1d_profile,0),
       nvl(video_slide_count_1d_profile,0),
       nvl(video_view_count_1d_profile,0),
       nvl(video_view_valid_count_1d_profile,0),
       nvl(video_view_time_1d_profile,0),
       nvl(video_view_finish_count_1d_profile,0),
       nvl(video_click_count_1d_follow,0),
       nvl(video_slide_count_1d_follow,0),
       nvl(video_view_count_1d_follow,0),
       nvl(video_view_valid_count_1d_follow,0),
       nvl(video_view_time_1d_follow,0),
       nvl(video_view_finish_count_1d_follow,0),
       nvl(video_click_count_1d_self,0),
       nvl(video_slide_count_1d_self,0),
       nvl(video_view_count_1d_self,0),
       nvl(video_view_valid_count_1d_self,0),
       nvl(video_view_time_1d_self,0),
       nvl(video_view_finish_count_1d_self,0),
       nvl(video_click_count_1d_push,0),
       nvl(video_slide_count_1d_push,0),
       nvl(video_view_count_1d_push,0),
       nvl(video_view_valid_count_1d_push,0),
       nvl(video_view_time_1d_push,0),
       nvl(video_view_finish_count_1d_push,0),
       nvl(video_like_count_1d,0),
       nvl(video_click_like_count_1d,0),
       nvl(video_double_click_like_count_1d,0),
       nvl(video_page_follow_count_1d,0),
       nvl(video_profile_click_count_1d,0),
       nvl(video_person_list_access_count_1d,0),
       nvl(comment_browse_amount_1d,0),
       nvl(comment_browse_time_1d,0),
       nvl(comment_send_count_1d,0),
       nvl(follow_count_1d,0),
       nvl(cancel_follow_count_1d,0),
       nvl(video_share_send_count_1d,0),
       nvl(video_download_count_1d,0),
       nvl(video_record_page_access_count_1d,0),
       nvl(video_record_count_1d,0),
       nvl(video_edit_page_access_count_1d,0),
       nvl(video_cover_edit_page_access_count_1d,0),
       nvl(video_music_select_page_access_count_1d,0),
       nvl(video_effect_edit_page_access_count_1d,0),
       nvl(video_time_magic_edit_page_access_count_1d,0),
       nvl(video_music_magic_edit_page_access_count_1d,0),
       nvl(video_title_edit_page_access_count_1d,0),
       nvl(video_publish_and_share_send_amount_1d,0),
       nvl(video_cutme_edit_page_access_count_1d,0),
       nvl(video_topic_use_amount_1d,0),
       nvl(video_publish_and_friend_at_amount_1d,0),
       nvl(video_publish_page_access_count_1d,0),
       nvl(video_publish_count_1d,0),
       nvl(video_publish_success_count_1d,0),
       nvl(video_draft_save_count_1d,0),
       nvl(video_duet_use_count_1d,0),
       nvl(video_sticker_use_count_1d,0),
       nvl(video_filter_use_count_1d,0),
       nvl(video_beauty_use_count_1d,0),
       nvl(video_thin_face_use_count_1d,0),
       nvl(video_music_magic_use_count_1d,0),
       nvl(video_body_magic_use_count_1d,0),
       nvl(video_3D_4D_magic_use_count_1d,0),
       nvl(video_effect_use_count_1d,0),
       nvl(video_boom_use_count_1d,0),
       nvl(video_original_sound_use_count_1d,0),
       nvl(video_official_music_use_count_1d,0),
       nvl(video_local_music_use_count_1d,0),
       nvl(video_subtitle_use_count_1d,0),
       nvl(video_title_use_count_1d,0),
       nvl(video_desc_info_use_count_1d,0),
       nvl(video_cutme_use_count_1d,0),
       nvl(live_time,0),
       nvl(live_watch,0),
       nvl(push_disp_cnt,0),
       nvl(push_click_cnt,0),
       nvl(login_state,0),
       nvl(his_acc_app_use_count,0),
       nvl(his_acc_app_use_days,0),
       nvl(his_acc_video_view_count,0),
       nvl(his_acc_video_view_finish_count,0),
       nvl(his_acc_video_view_time,0),
       nvl(his_acc_video_page_follow_count,0),
       nvl(his_acc_video_like_count,0),
       nvl(his_acc_video_person_list_access_count,0),
       nvl(his_acc_comment_send_count,0),
       nvl(his_acc_follow_count,0),
       nvl(his_acc_followed_count,0),
       nvl(his_acc_video_record_count,0),
       nvl(his_acc_video_publish_count,0),
       nvl(his_acc_video_publish_success_count,0),
       nvl(country,'unknown'),
       nvl(phone_lang,'unknown'),
       nvl(os,'unknown'),
       nvl(os_version,'unknown'),
       nvl(net,'unknown')
FROM
  (SELECT hdid,
          session_cnt,
          use_time,
          login_state,
          size(version_set) AS version_cnt
   FROM tmp.like_hdid_behavior_alive
   WHERE DAY='2019-07-29')t1
LEFT JOIN
  (SELECT hdid,
          video_click_count_1d,
          video_slide_count_1d,
          video_view_count_1d,
          video_view_valid_count_1d,
          video_view_time_1d,
          video_view_finish_count_1d,
          video_click_count_1d_hot,
          video_slide_count_1d_hot,
          video_view_count_1d_hot,
          video_view_valid_count_1d_hot,
          video_view_time_1d_hot,
          video_view_finish_count_1d_hot,
          video_click_count_1d_profile,
          video_slide_count_1d_profile,
          video_view_count_1d_profile,
          video_view_valid_count_1d_profile,
          video_view_time_1d_profile,
          video_view_finish_count_1d_profile,
          video_click_count_1d_follow,
          video_slide_count_1d_follow,
          video_view_count_1d_follow,
          video_view_valid_count_1d_follow,
          video_view_time_1d_follow,
          video_view_finish_count_1d_follow,
          video_click_count_1d_self,
          video_slide_count_1d_self,
          video_view_count_1d_self,
          video_view_valid_count_1d_self,
          video_view_time_1d_self,
          video_view_finish_count_1d_self,
          video_click_count_1d_push,
          video_slide_count_1d_push,
          video_view_count_1d_push,
          video_view_valid_count_1d_push,
          video_view_time_1d_push,
          video_view_finish_count_1d_push
   FROM tmp.like_hdid_behavior_vv)t2 ON t1.hdid=t2.hdid
LEFT JOIN
  (SELECT hdid,
          video_like_count_1d,
          video_click_like_count_1d,
          video_double_click_like_count_1d,
          video_page_follow_count_1d,
          video_profile_click_count_1d,
          video_person_list_access_count_1d,
          comment_browse_amount_1d,
          comment_browse_time_1d,
          comment_send_count_1d
   FROM tmp.like_hdid_behavior_vpage)t3 ON t1.hdid=t3.hdid
LEFT JOIN
  (SELECT hdid,
          follow_count_1d,
          cancel_follow_count_1d
   FROM tmp.like_hdid_behavior_follow)t4 ON t1.hdid=t4.hdid
LEFT JOIN
  (SELECT hdid,
          video_share_send_count_1d,
          video_download_count_1d
   FROM tmp.like_hdid_behavior_share)t5 ON t1.hdid=t5.hdid
LEFT JOIN
  (SELECT hdid,
          video_record_page_access_count_1d,
          video_record_count_1d,
          video_edit_page_access_count_1d,
          video_cover_edit_page_access_count_1d,
          video_music_select_page_access_count_1d,
          video_effect_edit_page_access_count_1d,
          video_time_magic_edit_page_access_count_1d,
          video_music_magic_edit_page_access_count_1d,
          video_title_edit_page_access_count_1d,
          video_publish_and_share_send_amount_1d,
          video_cutme_edit_page_access_count_1d,
          video_topic_use_amount_1d,
          video_publish_and_friend_at_amount_1d,
          video_publish_page_access_count_1d,
          video_publish_count_1d,
          video_publish_success_count_1d,
          video_draft_save_count_1d,
          video_duet_use_count_1d,
          video_sticker_use_count_1d,
          video_filter_use_count_1d,
          video_beauty_use_count_1d,
          video_thin_face_use_count_1d,
          video_music_magic_use_count_1d,
          video_body_magic_use_count_1d,
          video_3D_4D_magic_use_count_1d,
          video_effect_use_count_1d,
          video_boom_use_count_1d,
          video_original_sound_use_count_1d,
          video_official_music_use_count_1d,
          video_local_music_use_count_1d,
          video_subtitle_use_count_1d,
          video_title_use_count_1d,
          video_desc_info_use_count_1d,
          video_cutme_use_count_1d
   FROM tmp.like_hdid_behavior_produce)t6 ON t1.hdid=t6.hdid
LEFT JOIN
  (SELECT hdid,
          live_time,
          live_watch
   FROM tmp.like_hdid_behavior_live)t7 ON t1.hdid=t7.hdid
LEFT JOIN
  (SELECT hdid,
          push_disp_cnt,
          push_click_cnt
   FROM tmp.like_hdid_behavior_push)t8 ON t1.hdid=t8.hdid
LEFT JOIN
  (SELECT hdid,
          his_acc_app_use_count,
          his_acc_app_use_days
   FROM tmp.like_hdid_status_use)t9 ON t1.hdid=t9.hdid
LEFT JOIN
  (SELECT hdid,
          his_acc_video_view_count,
          his_acc_video_view_finish_count,
          his_acc_video_view_time
   FROM tmp.like_hdid_status_vv)t10 ON t1.hdid=t10.hdid
LEFT JOIN
  (SELECT hdid,
          his_acc_video_page_follow_count,
          his_acc_video_like_count,
          his_acc_video_person_list_access_count,
          his_acc_comment_send_count
   FROM tmp.like_hdid_status_vpage)t11 ON t1.hdid=t11.hdid
LEFT JOIN
  (SELECT hdid,
          his_acc_follow_count
   FROM tmp.like_hdid_status_follow)t12 ON t1.hdid=t12.hdid
LEFT JOIN
  (SELECT hdid,
          his_acc_followed_count
   FROM tmp.like_hdid_status_followed)t13 ON t1.hdid=t13.hdid
LEFT JOIN
  (SELECT hdid,
          his_acc_video_record_count,
          his_acc_video_publish_count,
          his_acc_video_publish_success_count
   FROM tmp.like_hdid_status_produce)t14 ON t1.hdid=t14.hdid
LEFT JOIN
  (SELECT hdid,
          country,
          phone_lang,
          os,
          os_version,
          net
   FROM tmp.like_hdid_status_common)t15 ON t1.hdid=t15.hdid