/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.util;

import com.google.common.collect.ImmutableList;
import io.airlift.bytecode.ClassDefinition;
import io.airlift.bytecode.DynamicClassLoader;
import io.airlift.bytecode.MethodDefinition;
import io.airlift.bytecode.ParameterizedType;
import io.airlift.log.Logger;
import io.trino.spi.TrinoException;
import org.objectweb.asm.MethodTooLargeException;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodHandles.Lookup;
import java.nio.file.Path;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import static io.airlift.bytecode.Access.FINAL;
import static io.airlift.bytecode.Access.PUBLIC;
import static io.airlift.bytecode.Access.STATIC;
import static io.airlift.bytecode.Access.a;
import static io.airlift.bytecode.BytecodeUtils.toJavaIdentifierString;
import static io.airlift.bytecode.ClassGenerator.classGenerator;
import static io.airlift.bytecode.HiddenClassGenerator.hiddenClassGenerator;
import static io.airlift.bytecode.ParameterizedType.type;
import static io.airlift.bytecode.ParameterizedType.typeFromJavaClassName;
import static io.airlift.bytecode.expression.BytecodeExpressions.invokeStatic;
import static io.trino.spi.StandardErrorCode.QUERY_EXCEEDED_COMPILER_LIMIT;
import static java.time.ZoneOffset.UTC;

public final class CompilerUtils
{
    private static final Logger log = Logger.get(CompilerUtils.class);

    private static final AtomicLong CLASS_ID = new AtomicLong();
    private static final DateTimeFormatter TIMESTAMP_FORMAT = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
    private static final String PACKAGE_PREFIX = "io.trino.$gen.";

    // Dumps every generated class to the directory and retains debug attributes in them.
    // Class names are only uniquified with a timestamp and counter when dumping, to keep
    // the dumped files apart: hidden classes cannot collide by name, so stable names are
    // used otherwise, keeping constant pool symbols short and generated bytes deterministic.
    private static final Optional<Path> DUMP_CLASSES_DIRECTORY = Optional.ofNullable(System.getProperty("trino.compiler.dump-classes-directory")).map(Path::of);
    // Maximum symbol table entry allowed by the JVM class file format
    private static final int MAX_SYMBOL_TABLE_ENTRY_LENGTH = 65535;
    // Leave enough of a buffer between the maximum generated class name length and the symbol table limit
    // so that method handles and other symbols that embed the class name can be encoded without failing
    private static final int MAX_CLASS_NAME_LENGTH = MAX_SYMBOL_TABLE_ENTRY_LENGTH - 8192;

    // A hidden class must be defined by a lookup whose class is in the same run-time package,
    // and a source file cannot be placed in io.trino.$gen, so generate an anchor class there
    private static final Lookup GENERATED_CLASS_LOOKUP = createGeneratedClassLookup(new DynamicClassLoader(CompilerUtils.class.getClassLoader()));

    // Generated classes that implement plugin interfaces (e.g. aggregation state classes) must
    // be defined by a lookup whose loader sees both the plugin and the engine classes. Anchors
    // are cached per accessed class, so their lifecycle follows the plugin classloader.
    private static final ClassValue<Lookup> ACCESSIBLE_CLASS_LOOKUPS = new ClassValue<>()
    {
        @Override
        protected Lookup computeValue(Class<?> type)
        {
            return createGeneratedClassLookup(new DynamicClassLoader(type.getClassLoader(), CompilerUtils.class.getClassLoader()));
        }
    };

    private CompilerUtils() {}

    private static Lookup createGeneratedClassLookup(DynamicClassLoader classLoader)
    {
        ClassDefinition anchor = new ClassDefinition(
                a(PUBLIC, FINAL),
                typeFromJavaClassName(PACKAGE_PREFIX + "GeneratedClassLookupAnchor"),
                type(Object.class));
        MethodDefinition lookupMethod = anchor.declareMethod(a(PUBLIC, STATIC), "lookup", type(Lookup.class));
        // MethodHandles.lookup() is caller sensitive: invoked from the anchor, it returns
        // a full-privilege lookup of the anchor class
        lookupMethod.getBody()
                .append(invokeStatic(MethodHandles.class, "lookup", Lookup.class).ret());

        Class<?> anchorClass = classGenerator(classLoader).defineClass(anchor, Object.class);
        try {
            return (Lookup) anchorClass.getMethod("lookup").invoke(null);
        }
        catch (ReflectiveOperationException e) {
            throw new AssertionError(e);
        }
    }

    public static ParameterizedType makeClassName(String baseName, Optional<String> suffix)
    {
        String classNameSuffix = "";
        if (DUMP_CLASSES_DIRECTORY.isPresent()) {
            classNameSuffix = "_" + suffix.orElseGet(() -> Instant.now().atZone(UTC).format(TIMESTAMP_FORMAT)) + "_" + CLASS_ID.incrementAndGet();
        }

        int addedNameLength = PACKAGE_PREFIX.length() + classNameSuffix.length();

        // truncate the baseName to ensure that we don't exceed the bytecode limit on class names, while also ensuring
        // the class suffix and unique ID are fully preserved to avoid conflicts with other generated class names
        if (baseName.length() + addedNameLength > MAX_CLASS_NAME_LENGTH) {
            baseName = baseName.substring(0, MAX_CLASS_NAME_LENGTH - addedNameLength);
        }

        return typeFromJavaClassName(PACKAGE_PREFIX + toJavaIdentifierString(baseName + classNameSuffix));
    }

    public static ParameterizedType makeClassName(String baseName)
    {
        return makeClassName(baseName, Optional.empty());
    }

    public static <T> Class<? extends T> defineClass(ClassDefinition classDefinition, Class<T> superType, Map<Long, MethodHandle> callSiteBindings, ClassLoader parentClassLoader)
    {
        return defineClass(classDefinition, superType, new DynamicClassLoader(parentClassLoader, callSiteBindings));
    }

    public static <T> Class<? extends T> defineClass(ClassDefinition classDefinition, Class<T> superType, DynamicClassLoader classLoader)
    {
        log.debug("Defining class: %s", classDefinition.getName());
        try {
            return classGenerator(classLoader)
                    .omitDebugInfo(DUMP_CLASSES_DIRECTORY.isEmpty())
                    .dumpClassFilesTo(DUMP_CLASSES_DIRECTORY)
                    .defineClass(classDefinition, superType);
        }
        catch (MethodTooLargeException e) {
            throw new TrinoException(QUERY_EXCEEDED_COMPILER_LIMIT, "Query exceeded maximum method size.", e);
        }
    }

    /**
     * Defines the class as a hidden class with the call site bindings attached as class data.
     * The generated bytecode reads bindings back through {@code MethodHandles.classData}, so
     * no {@link DynamicClassLoader} is created and the class unloads independently once it
     * becomes unreachable. The class must not be referenced by name from other classes.
     */
    public static <T> Class<? extends T> defineHiddenClass(ClassDefinition classDefinition, Class<T> superType, List<Object> classData)
    {
        return defineHiddenClass(classDefinition, superType, GENERATED_CLASS_LOOKUP, classData);
    }

    /**
     * Variant for generated classes that reference classes only visible from another classloader,
     * e.g. aggregation state classes implementing a plugin-defined state interface:
     * {@code accessedClass}'s loader is consulted before the engine classloader.
     */
    public static <T> Class<? extends T> defineHiddenClass(ClassDefinition classDefinition, Class<T> superType, Class<?> accessedClass, List<Object> classData)
    {
        Lookup lookup = GENERATED_CLASS_LOOKUP;
        ClassLoader accessedLoader = accessedClass.getClassLoader();
        if (accessedLoader != null && accessedLoader != CompilerUtils.class.getClassLoader()) {
            lookup = ACCESSIBLE_CLASS_LOOKUPS.get(accessedClass);
        }
        return defineHiddenClass(classDefinition, superType, lookup, classData);
    }

    private static <T> Class<? extends T> defineHiddenClass(ClassDefinition classDefinition, Class<T> superType, Lookup lookup, List<Object> classData)
    {
        log.debug("Defining hidden class: %s", classDefinition.getName());
        try {
            // production servers never inspect SourceFile, LineNumberTable, or LocalVariableTable
            return hiddenClassGenerator(lookup)
                    .omitDebugInfo(DUMP_CLASSES_DIRECTORY.isEmpty())
                    .dumpClassFilesTo(DUMP_CLASSES_DIRECTORY)
                    .defineHiddenClass(classDefinition, superType, Optional.of(ImmutableList.copyOf(classData)));
        }
        catch (MethodTooLargeException e) {
            throw new TrinoException(QUERY_EXCEEDED_COMPILER_LIMIT, "Query exceeded maximum method size.", e);
        }
    }
}
