/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.trino.plugin.eventlistener.mysql;

import org.jdbi.v3.sqlobject.customizer.BindMethods;
import org.jdbi.v3.sqlobject.statement.SqlQuery;
import org.jdbi.v3.sqlobject.statement.SqlUpdate;

public interface QueryDao
{
    @SqlUpdate(
            """
            CREATE TABLE IF NOT EXISTS trino_queries (
              query_id VARCHAR(255) NOT NULL PRIMARY KEY,
              create_time DATETIME(3) NULL,
              transaction_id VARCHAR(255) NULL,
              query MEDIUMTEXT NOT NULL,
              update_type VARCHAR(255) NULL,
              prepared_query MEDIUMTEXT NULL,
              query_state VARCHAR(255) NOT NULL,
              plan MEDIUMTEXT NULL,
              stage_info_json MEDIUMTEXT NULL,
              user VARCHAR(255) NOT NULL,
              principal VARCHAR(255) NULL,
              trace_token VARCHAR(255) NULL,
              remote_client_address VARCHAR(255) NULL,
              user_agent VARCHAR(255) NULL,
              client_info MEDIUMTEXT NULL,
              client_tags_json MEDIUMTEXT NOT NULL,
              source VARCHAR(255) NULL,
              catalog VARCHAR(255) NULL,
              `schema` VARCHAR(255) NULL,
              resource_group_id VARCHAR(255) NULL,
              session_properties_json MEDIUMTEXT NOT NULL,
              server_address VARCHAR(255) NOT NULL,
              server_version VARCHAR(255) NOT NULL,
              environment VARCHAR(255) NOT NULL,
              query_type VARCHAR(255) NULL,
              inputs_json MEDIUMTEXT NOT NULL,
              output_json MEDIUMTEXT NULL,
              error_code VARCHAR(255) NULL,
              error_type VARCHAR(255) NULL,
              failure_type VARCHAR(255) NULL,
              failure_message MEDIUMTEXT NULL,
              failure_task VARCHAR(255) NULL,
              failure_host VARCHAR(255) NULL,
              failures_json MEDIUMTEXT NULL,
              warnings_json MEDIUMTEXT NOT NULL,
              cpu_time_millis BIGINT NOT NULL,
              failed_cpu_time_millis BIGINT NOT NULL,
              wall_time_millis BIGINT NOT NULL,
              queued_time_millis BIGINT NOT NULL,
              scheduled_time_millis BIGINT NOT NULL,
              failed_scheduled_time_millis BIGINT NOT NULL,
              waiting_time_millis BIGINT NOT NULL,
              analysis_time_millis BIGINT NOT NULL,
              planning_time_millis BIGINT NOT NULL,
              planning_cpu_time_millis BIGINT NOT NULL,
              starting_time_millis BIGINT NOT NULL,
              execution_time_millis BIGINT NOT NULL,
              input_blocked_time_millis BIGINT NOT NULL,
              failed_input_blocked_time_millis BIGINT NOT NULL,
              output_blocked_time_millis BIGINT NOT NULL,
              failed_output_blocked_time_millis BIGINT NOT NULL,
              physical_input_read_time_millis BIGINT NOT NULL,
              peak_memory_bytes BIGINT NOT NULL,
              peak_task_memory_bytes BIGINT NOT NULL,
              physical_input_bytes BIGINT NOT NULL,
              physical_input_rows BIGINT NOT NULL,
              internal_network_bytes BIGINT NOT NULL,
              internal_network_rows BIGINT NOT NULL,
              total_bytes BIGINT NOT NULL,
              total_rows BIGINT NOT NULL,
              output_bytes BIGINT NOT NULL,
              output_rows BIGINT NOT NULL,
              written_bytes BIGINT NOT NULL,
              written_rows BIGINT NOT NULL,
              cumulative_memory DOUBLE NOT NULL,
              failed_cumulative_memory DOUBLE NOT NULL,
              completed_splits BIGINT NOT NULL,
              retry_policy VARCHAR(255) NOT NULL,
              operator_summaries_json MEDIUMTEXT NOT NULL
            )
            DEFAULT CHARACTER SET utf8""")
    void createTable();

    @SqlQuery(
            """
            SELECT COUNT(*) FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'trino_queries'
              AND column_name = 'create_time'""")
    int countCreateTimeColumn();

    @SqlUpdate("ALTER TABLE trino_queries ADD COLUMN create_time DATETIME(3) NULL AFTER query_id")
    void addCreateTimeColumn();

    @SqlUpdate(
            """
            INSERT INTO trino_queries (
              query_id,
              create_time,
              transaction_id,
              query,
              update_type,
              prepared_query,
              query_state,
              plan,
              stage_info_json,
              user,
              principal,
              trace_token,
              remote_client_address,
              user_agent,
              client_info,
              client_tags_json,
              source,
              catalog,
              `schema`,
              resource_group_id,
              session_properties_json,
              server_address,
              server_version,
              environment,
              query_type,
              inputs_json,
              output_json,
              error_code,
              error_type,
              failure_type,
              failure_message,
              failure_task,
              failure_host,
              failures_json,
              warnings_json,
              cpu_time_millis,
              failed_cpu_time_millis,
              wall_time_millis,
              queued_time_millis,
              scheduled_time_millis,
              failed_scheduled_time_millis,
              waiting_time_millis,
              analysis_time_millis,
              planning_time_millis,
              planning_cpu_time_millis,
              starting_time_millis,
              execution_time_millis,
              input_blocked_time_millis,
              failed_input_blocked_time_millis,
              output_blocked_time_millis,
              failed_output_blocked_time_millis,
              physical_input_read_time_millis,
              peak_memory_bytes,
              peak_task_memory_bytes,
              physical_input_bytes,
              physical_input_rows,
              internal_network_bytes,
              internal_network_rows,
              total_bytes,
              total_rows,
              output_bytes,
              output_rows,
              written_bytes,
              written_rows,
              cumulative_memory,
              failed_cumulative_memory,
              completed_splits,
              retry_policy,
              operator_summaries_json
            )
            VALUES (
              :queryId,
              :createTime,
              :transactionId,
              :query,
              :updateType,
              :preparedQuery,
              :queryState,
              :plan,
              :stageInfoJson,
              :user,
              :principal,
              :traceToken,
              :remoteClientAddress,
              :userAgent,
              :clientInfo,
              :clientTagsJson,
              :source,
              :catalog,
              :schema,
              :resourceGroupId,
              :sessionPropertiesJson,
              :serverAddress,
              :serverVersion,
              :environment,
              :queryType,
              :inputsJson,
              :outputJson,
              :errorCode,
              :errorType,
              :failureType,
              :failureMessage,
              :failureTask,
              :failureHost,
              :failuresJson,
              :warningsJson,
              :cpuTimeMillis,
              :failedCpuTimeMillis,
              :wallTimeMillis,
              :queuedTimeMillis,
              :scheduledTimeMillis,
              :failedScheduledTimeMillis,
              :waitingTimeMillis,
              :analysisTimeMillis,
              :planningTimeMillis,
              :planningCpuTimeMillis,
              :startingTimeMillis,
              :executionTimeMillis,
              :inputBlockedTimeMillis,
              :failedInputBlockedTimeMillis,
              :outputBlockedTimeMillis,
              :failedOutputBlockedTimeMillis,
              :physicalInputReadTimeMillis,
              :peakMemoryBytes,
              :peakTaskMemoryBytes,
              :physicalInputBytes,
              :physicalInputRows,
              :internalNetworkBytes,
              :internalNetworkRows,
              :totalBytes,
              :totalRows,
              :outputBytes,
              :outputRows,
              :writtenBytes,
              :writtenRows,
              :cumulativeMemory,
              :failedCumulativeMemory,
              :completedSplits,
              :retryPolicy,
              :operatorSummariesJson
            )""")
    void store(@BindMethods QueryEntity entity);
}
