---
name: Bug report 🐞
description: Problems, bugs and issues with Trino
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        * Verify that the issue is not already reported, looking at the [currently open issues](https://github.com/trinodb/trino/issues), use the `Filter` field to narrow down your search.
        * **Possible security vulnerabilities**: STOP here and contact `security@trino.io` instead!
        * Do **NOT** share any sensitive information like passwords, security tokens, private URLs etc.

  - type: input
    attributes:
      label: Trino version
      description: Which Trino server version are you using?
      placeholder: "Run `SELECT version();` on your Trino server"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Please describe the bug
      description: Describe the problem, minimal steps to reproduce, expected and actual behaviors. if something fails, include the stacktrace. You can include additional files by dragging and dropping them here.
    validations:
      required: true
