# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.177.0/containers/java/.devcontainer/base.Dockerfile

ARG BASE_IMAGE_TAG
FROM uchimera.azurecr.io/cccs/dev/trino-build:${BASE_IMAGE_TAG}
