connector.name=iceberg
hive.metastore.uri=thrift://hadoop-master:9083
iceberg.register-table-procedure.enabled=true
iceberg.allowed-extra-properties=*
iceberg.encryption.kms-type=AWS
aws.kms.region=us-east-1
aws.kms.endpoint=http://localstack:4566
aws.kms.access-key=test
aws.kms.secret-key=test
fs.hadoop.enabled=true
