databases:
  trino:
    host: presto-master.docker.cluster
    port: 7778
    http_port: 8080
    https_port: ${databases.trino.port}
    server_address: https://${databases.trino.host}:${databases.trino.port}
    jdbc_url: "jdbc:trino://${databases.trino.host}:${databases.trino.port}/hive/${databases.hive.schema}?\
      SSL=true&\
      SSLTrustStorePath=${databases.trino.https_keystore_path}&\
      SSLTrustStorePassword=${databases.trino.https_keystore_password}"
    configured_hdfs_user: hive
    https_keystore_path: /docker/trino-product-tests/conf/trino/etc/docker.cluster.jks
    https_keystore_password: '123456'
