Bootstrap=WARN
io.trino.bootstrap=WARN
io.trino.event.QueryMonitor=WARN
io.trino.server.PluginManager=WARN
io.trino.connector.CatalogStoreManager=WARN
io.prestosql.server.PluginManager=WARN
org.eclipse.jetty=WARN
org.apache.iceberg=WARN
org.apache.iceberg.util.Tasks=ERROR
org.apache.parquet=WARN
org.hibernate.validator.internal.util.Version=WARN
io.trino.memory.RemoteNodeMemory=ERROR
io.trino.simd.BlockEncodingSimdSupport=WARN
org.ishugaliy.allgood.consistent.hash.HashRing=WARN
io.confluent.kafka=WARN
org.apache.kafka=WARN
io.trino.server.security.oauth2=DEBUG
