name: "starburst-init-action"
description: "Perform common initialization steps for Starburst specific workflow"
inputs:
  aws-access-key-id:
    description: "Access key id for login to AWS"
    required: true
  aws-secret-access-key:
    description: "Secret access key for login to AWS"
    required: true
  secret-id:
    description: "Id of secret from AWS Secrets Manager to use"
    required: true
  aws-region:
    description: "Default AWS region to use"
    required: false
    default: "us-east-2"
  login-maven:
    description: "Should we login to codeartifact?"
    required: false
    default: "true"
  login-docker:
    description: "Should we login to ecr?"
    required: false
    default: "false"

outputs:
  run-job:
    description: "Should job run?"
    value: ${{ steps.job-should-run.outputs.run-job }}

runs:
  using: composite
  steps:
    - name: "GHA Node Info"
      shell: bash
      run: |
        echo " *** Runner info"
        curl -SsL --retry 3 http://instance-data/latest/dynamic/instance-identity/document || true
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        # longest job that uses this action has a timeout of 130 minutes, so add some margin
        role-duration-seconds: 8000
    - name: "Show AWS user"
      shell: bash
      run: |
        echo " *** AWS user info"
        aws sts get-caller-identity
    - name: "Fetch secrets"
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: ${{ inputs.secret-id }}
        parse-json-secrets: true
    - name: "Login to maven registry"
      if: inputs.login-maven != 'false'
      uses: starburstdata/codeartifact-login-action@v1
      with:
        domain: starburstdata-sep-cicd
        owner: 843985043183
        region: us-east-2
    - name: "Login to ECR docker registry"
      if: inputs.login-docker != 'false'
      uses: docker/login-action@v3
      env:
        DOCKER_REGISTRY: "843985043183.dkr.ecr.us-east-2.amazonaws.com"
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
    - name: "Login to ECR pull-through cache"
      if: inputs.login-docker != 'false'
      shell: bash
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 843985043183.dkr.ecr.us-east-1.amazonaws.com
    - name: "Login to docker hub"
      if: inputs.login-docker != 'false'
      uses: docker/login-action@v3
      with:
        username: ${{ env.SEP_CI_SEP_DOCKERHUBUSERNAME }}
        password: ${{ env.SEP_CI_SEP_DOCKERHUBPASSWORD }}
