name: CLA

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created]
  merge_group:
    types: [checks_requested]

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  check:
    if: |
      github.repository == 'trinodb/trino' &&
      (
        github.event_name != 'issue_comment' ||
        (
          github.event.issue.pull_request &&
          contains(fromJson('["COLLABORATOR", "MEMBER", "OWNER"]'), github.event.comment.author_association) &&
          (
            contains(github.event.comment.body, '@cla-bot check') ||
            contains(github.event.comment.body, '/cla-check')
          )
        )
      )
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false
      - name: Check CLA
        run: node .github/bin/check-cla.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
